# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-07 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='CheckIn',
        ),
    ]
